### PR TITLE
Initialise map before graphics

### PR DESCRIPTION
**Pull request by fangyi-zhou**

### CODE REVIEW

**Comment by MislankaNova** [comment]
The `main` function is currently a mess. It needs a more through clean-up and de-coupling in my opinion. The sequence in which things happen should be more organised by then.

As for this specific PR, if the `GEO_NewGeo` call within `while (running)` is removed then when spacebar is pressed, the program will not generate a new map as it previously would.

There have been no document which should inform you of these operations and I apologise for that.

**Comment by fangyi-zhou** [comment]
Interesting, I didn't discover spacekey regenerates a new map

**Comment by fangyi-zhou** [comment]
This PR was intended to fix the issue that SDL captures the exit signals so that Ctrl-C will not terminate the program during initial map generation. Moving the initialisation of Geo before SDL prevents this from happening, as the signal capture takes place during SDL initialisation.

I'm investigating into a way to terminate the program during geo generation. Currently polling only takes place after generation is complete and `alive` loop is being run. I'll see if I can find a way to allow killing during generation.

**Comment by MislankaNova** [comment]
The easiest way would be to open the window only when the generation is finished, and close it before generating the map afresh. For some reason I did not write the code in this way, and now the window freezes while generation is running, which is awkward.

I'll fix it when `main` is re-written.

**Comment by fangyi-zhou** [comment]
I don’t think that will fix the problem.

The issue is that termination is only triggered when the SDL_QUIT event is polled and handled. In your proposed solution, if there is some work ongoing, the SDL_QUIT event will not be handled and the program is not terminated properly.

**Pull request closed without merging**
